### ISSUE TITLE
CRC does not match

### ISSUE THREAD

**Issue by Marsfan** [esp8266/Arduino#1178]
I just tried to download the esp files into the Arduino IDE and it reported this error.
`Caused by: java.lang.Exception: CRC doesn't match. File is corrupted.`

Further details explained by Arduino log

` CRC doesn't match. File is corrupted.
java.lang.RuntimeException: java.lang.Exception: CRC doesn't match. File is corrupted.
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$24(ContributionManagerUI.java:170)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: CRC doesn't match. File is corrupted.
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:77)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:110)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$24(ContributionManagerUI.java:164)
	... 1 more`

**Comment by igrr** [comment]
You need to open your `Arduino15/staging/packages` directory (that's in AppData on Windows, ~/. on Linux and ~/Library/ on Mac) and delete files which got partially downloaded.
