### ISSUE TITLE
Only one Error Left

### ISSUE THREAD

**Issue by parasshah143** [esp8266/Arduino#1979]

**Comment by igrr** [comment]
Judging by the `packages\wemos\hardware\esp8266\1.0.4` part, you seem to be using an outdated ESP8266 package from Wemos. Please remove that (`C:\Users\Paras.Shah\AppData\Local\Arduino15\packages\wemos`) and use the following boards manager package URL:
`http://arduino.esp8266.com/stable/package_esp8266com_index.json`.

**Comment by parasshah143** [comment]
Thank for your help. Need more help from you.

Question 1:
Can you please tell me what Ip i should write for Ntp server Asia? 
From internet I could find the server name but not Ip.

Question 2:

While Compiling I am facing error:
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658) 

Looking forward to your response.

Thanks,
Paras Shah

**Comment by parasshah143** [comment]
.error: failed sending 1055 bytes
.error: failed sending 1054 bytes
.error: failed sending 1054 bytes
.error: failed sending 1052 bytes
.error: failed sending 1055 bytes
.error: failed sending 1053 bytes
.error: failed sending 1051 bytes
.error: failed sending 1076 bytes
.error: failed sending 1071 bytes
.error: failed sending 1065 bytes
.error: failed sending 1078 bytes
warning: espcomm_send_command: didn't receive command response
warning: espcomm_send_command(FLASH_DOWNLOAD_DATA) failed
warning: espcomm_send_command: wrong direction/command: 0x01 0x03, expected 0x01 0x04
![arduino_error](https://cloud.githubusercontent.com/assets/18476869/14908205/d099589c-0df1-11e6-823e-4bdb3c62b866.png)

**Comment by parasshah143** [comment]
![successful_compiling](https://cloud.githubusercontent.com/assets/18476869/14908242/72954d5e-0df2-11e6-8904-c94971d207a4.png)
