### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by Pablotis** [esp8266/Arduino#211]
If I try to upload anything to the esp8266 it outputs that:
Sketch uses 196.464 bytes (37%) of program storage space. Maximum is 524.288 bytes.
java.lang.NullPointerException
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingProgrammer(SerialUploader.java:246)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:75)
	at processing.app.debug.Compiler.upload(Compiler.java:157)
	at processing.app.Sketch.upload(Sketch.java:1259)
	at processing.app.Sketch.exportApplet(Sketch.java:1201)
	at processing.app.Sketch.exportApplet(Sketch.java:1173)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2432)
	at java.lang.Thread.run(Thread.java:745)

I have tried the same connections with the ES8266 Flash Downloader and the AT commands firmware and it uploaded succesfully.
Can I also get the Bin files and flash them with the flasher tool? I have found them but there are two, i have tried flashing each on its address but it doesn't work.
Thanks!

**Comment by Pablotis** [comment]
Fixed
