### ISSUE TITLE
error compile git version tools

### ISSUE THREAD

**Issue by sparrowjack** [esp8266/Arduino#2676]
#### Hardware
Hardware:			ESP-12E
Platform                         macOS 10.12.1
Git Version:      	master branch with 4897e0006b5b0123a2fa31f67b14a3fff65ce561

### Description

I was trying to use git version library on a new MBP,because the stable version have some issues that matter with my project. So I cloned the repository,but can't run "python get.py" command,
 ```python
Downloading esptool-0.4.9-osx.tar.gz
Done
Hash mismatch for dist/esptool-0.4.9-osx.tar.gz, delete the file and try again
Traceback (most recent call last):
  File "get.py", line 116, in <module>
    get_tool(tool)
  File "get.py", line 83, in get_tool
    raise RuntimeError()
RuntimeError
```

I also tried to remove hash check, but it told me that the filetype  is not gzip file, so I got confused.
I had done before, so I checkout git repo to the former commit, still helpless.

So I wonder if you have any ideas?  

Thanks!

**Comment by sparrowjack** [comment]
the platform is  macOS 10.12.1

**Comment by sparrowjack** [comment]
```python
python get.py 
Platform: x86_64-apple-darwin
Downloading esptool-0.4.9-osx.tar.gz
Done
Hash mismatch for dist/esptool-0.4.9-osx.tar.gz, delete the file and try again
Traceback (most recent call last):
  File "get.py", line 116, in <module>
    get_tool(tool)
  File "get.py", line 83, in get_tool
    raise RuntimeError()
RuntimeError
```

**Comment by sparrowjack** [comment]
I just solve this problem by downloading esptool directly from https://github.com/igrr/esptool-ck/releases/download/0.4.9/esptool-0.4.9-osx.tar.gz, then put it to ./tools/dist directory.

And just run python get.py it will begin installation.

I don't know why this happened,may be the OS X bug for cmd environment or sth I had missing for compile.

You should aware that if you download with your browser,it is likely to unarchive it to .tar file, the you may need to get the original file from your Trash.

Hope this could help.
