### ISSUE TITLE
espota.py port to Java - Error[3]: Receive Failed

### ISSUE THREAD

**Issue by Hokyjack** [esp8266/Arduino#5045]
### Basic Infos

- [ x ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ x ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ x ] I have tested that the issue is present in current master branch (aka latest git).
- [ x ] I have searched the issue tracker for a similar issue.
- [ x ] If there is a stack dump, I have decoded it.
- [ x ] I have filled out all fields below.

#### Platform

- Hardware:				[ESP-12]
- Core Version:			[2.4.2]
- Development Env:		[Platformio|]
- Operating System:		[Debian]

### Settings in IDE

- Module:  			[Nodemcu]
- Flash Mode:			[qio]
- Flash Size: 		[4MB]
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80MHz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

I want to flash OTA update using Java code (to be later used from Android),
and since I didn't found any existing approach I decided to rewrite espota.py script into Java.

I've managed to successfully excahnge datagram packets and begin file upload,
but uploading fail every time at various stages: e.g: 27 %, with **Error[3]: Receive Failed** on ESP side, and **java.net.SocketException: Broken pipe (Write failed)** on Java side.

When triyng with espota.py with same settings, the OTA finish without any problem.

### Java 

```java

import java.io.*;
import java.net.*;
import org.apache.commons.codec.digest.DigestUtils;

public class SocketTest {

    public static void main(String[] args) {
        System.out.println("Starting Java server");
        UDPThread udp = new UDPThread();
        udp.start();
    }
}

class UDPThread extends Thread {
    
    private final static int LOCAL_PORT = 10000;
    private final static String REMOTE_ADDRESS = "192.168.1.11";
    private final static int REMOTE_PORT = 3232;
    
    public void run() {
        try {
            File f = new File("/home/hoky/ota2/firmware.bin");
            long fileLength = f.length();
            FileInputStream fis = new FileInputStream(f);
            String md5 = DigestUtils.md5Hex(fis);
            fis.close();


            ServerSocket serverSocket = new ServerSocket(LOCAL_PORT);

            DatagramSocket datagramSocket = new DatagramSocket(LOCAL_PORT);
            System.out.printf("Listening on udp:%s:%d%n", InetAddress.getLocalHost().getHostAddress(), LOCAL_PORT);

            byte[] receiveData = new byte[8];
            DatagramPacket receivePacket = new DatagramPacket(receiveData, receiveData.length);

            InetAddress IPAddress = InetAddress.getByName(REMOTE_ADDRESS);
            String sendString = "0 " + LOCAL_PORT + " " + fileLength + " " + md5;
            byte[] sendData = sendString.getBytes("UTF-8");
            DatagramPacket sendPacket = new DatagramPacket(sendData, sendData.length, IPAddress, REMOTE_PORT);
            datagramSocket.send(sendPacket);

            datagramSocket.receive(receivePacket);
            String sentence = new String(receivePacket.getData(), 0,
                    receivePacket.getLength());
            
            if (sentence.equals("OK")) {
                System.out.println("Starting upload ...");
                Socket socket = serverSocket.accept();

                uploadFile(f, socket);
            }
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }

    private void uploadFile(final File f, Socket socket) throws IOException {
        int count;
        long lenghtOfFile = f.length();
        long total = 0;
        final BufferedOutputStream outStream = new BufferedOutputStream(socket.getOutputStream());
        final BufferedInputStream inStream = new BufferedInputStream(new FileInputStream(f));
        final byte[] buffer = new byte[1024];

        socket.setSoTimeout(10000);

        while ((count = inStream.read(buffer)) > 0) {

            outStream.write(buffer, 0, count);
            total += 1024;
            System.out.println("Uploading: "+(int)((total*100)/lenghtOfFile) + "%");
        }
        System.out.println("done uploading");
        inStream.close();
        outStream.close();
    }
}
```
### ESP Sketch
```cpp
#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <WiFiUdp.h>
#include <ArduinoOTA.h>

const char* ssid = "";
const char* password = "";

void setup() {
    Serial.begin(115200);
    Serial.println("Booting, Version 1");

    WiFi.mode(WIFI_STA);
    WiFi.begin(ssid, password);

    while (WiFi.waitForConnectResult() != WL_CONNECTED) {
        Serial.println("Connection Failed! Rebooting...");
        delay(5000);
        ESP.restart();
}

  ArduinoOTA
    .onStart([]() {
      String type;
      if (ArduinoOTA.getCommand() == U_FLASH)
        type = "sketch";
      else // U_SPIFFS
        type = "filesystem";
      Serial.println("Start updating " + type);
    })
    .onEnd([]() {
      Serial.println("\nEnd");
    })
    .onProgress([](unsigned int progress, unsigned int total) {
      Serial.printf("Progress: %u%%\n", (progress / (total / 100)));
    })
    .onError([](ota_error_t error) {
      Serial.printf("Error[%u]: ", error);
      if (error == OTA_AUTH_ERROR) Serial.println("Auth Failed");
      else if (error == OTA_BEGIN_ERROR) Serial.println("Begin Failed");
      else if (error == OTA_CONNECT_ERROR) Serial.println("Connect Failed");
      else if (error == OTA_RECEIVE_ERROR) Serial.println("Receive Failed");
      else if (error == OTA_END_ERROR) Serial.println("End Failed");
    });

  ArduinoOTA.begin();
}

void loop() {
    ArduinoOTA.handle();
}
```

### Debug Messages

ESP Output
```
...
10:17.125302 	 Progress: 23%
10:17.125747 	 Progress: 23%
10:17.188817 	 Progress: 23%
10:17.193381 	 Progress: 24%
10:17.193819 	 Progress: 24%
10:17.244029 	 Progress: 24%
10:17.244432 	 Progress: 24%
10:21.247505 	 Error[3]: Receive Failed
```
Java Output
```
...
Uploading: 26%
Uploading: 26%
Uploading: 27%
Uploading: 27%
Uploading: 27%
Uploading: 27%
Uploading: 27%
Uploading: 27%
Uploading: 27%
Uploading: 27%
java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
	at UDPThread.uploadFile(SocketTest.java:81)
	at UDPThread.run(SocketTest.java:62)
```

**Comment by devyte** [comment]
This sounds interesting, and I'd love to see the final result, but it is outside the scope of this core or issue tracker.
As strictly WAGs, and assuming that your java code really is equivalent to the python one, you could have some kind of timing issue, e.g.: you take too long to send a chunk and the connection times out, or  it could be a buffering issue on your end.
Closing.

**Comment by Hokyjack** [comment]
@devyte 
I've just found the issue: seems when using Java the data are being sent in "batches" and not so fluidly as in python way, and sometimes the pause is more than 1000 milliseconds as is defined in ArduinoOTA (_ota_timeout). Changing this value to 5000 seems to fix the issue.

One question: Is there any way to change the **_ota_timeout** from sketch, or I need to hard set it in ArduinoOTA source code?

Thank you.

**Comment by devyte** [comment]
I don't know, but I at first glance I don't see an interface for a timeout.
