### ISSUE TITLE
ESP8622 ESP-201 esptool.FatalError

### ISSUE THREAD

**Issue by rserroyen** [esp8266/Arduino#7239]
Hello

I use an ESP8622 ESP-201 but I can't program it!

I use a USB CH340 to TTL and mounting [https://www.hackster.io/Hulkco/esp-201-esp8266-temperature-humidity-web-server-9f2fa9](url)

I tested the WiFiWebServer but the upload does not work

I tested different speed values but without success

why

thank you

I had a stroke! I do not write well: oops: !!

`
I had a stroke! I do not write well: oops: !!

`Executable segment sizes:

IROM   : 279880          - code in flash         (default or ICACHE_FLASH_ATTR) 

IRAM   : 27692   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 

DATA   : 1264  )         - initialized variables (global, static) in RAM/HEAP 

RODATA : 1008  ) / 81920 - constants             (global, static) in RAM/HEAP 

BSS    : 25352 )         - zeroed variables      (global, static) in RAM/HEAP 

Le croquis utilise 309844 octets (29%) de l'espace de stockage de programmes. Le maximum est de 1044464 octets.
Les variables globales utilisent 27624 octets (33%) de mémoire dynamique, ce qui laisse 54296 octets pour les variables locales. Le maximum est de 81920 octets.
esptool.py v2.8
Serial port COM6
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 5c:cf:7f:01:eb:82
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 1MB
Flash params set to 0x0020
Compressed 314000 bytes to 225581...

Writing at 0x00000000... (7 %)
Writing at 0x00004000... (14 %)
Writing at 0x00008000... (21 %)
Writing at 0x0000c000... (28 %)
Writing at 0x00010000... (35 %)
Writing at 0x00014000... (42 %)
Writing at 0x00018000... (50 %)
Writing at 0x0001c000... (57 %)
Writing at 0x00020000... (64 %)
Writing at 0x00024000... (71 %)
Writing at 0x00028000... (78 %)
Writing at 0x0002c000... (85 %)
Writing at 0x00030000... (92 %)
Writing at 0x00034000... (100 %)
Wrote 314000 bytes (225581 compressed) at 0x00000000 in 19.9 seconds (effective 126.0 kbit/s)...
Traceback (most recent call last):
  File "C:\Users\rserr\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2/tools/upload.py", line 65, in <module>
    esptool.main(cmdline)
  File "C:/Users/rserr/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.6.2/tools/esptool\esptool.py", line 2938, in main
    operation_func(esp, args)
  File "C:/Users/rserr/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.6.2/tools/esptool\esptool.py", line 2398, in write_flash
    res = esp.flash_md5sum(address, uncsize)
  File "C:/Users/rserr/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.6.2/tools/esptool\esptool.py", line 104, in inner
    return func(*args, **kwargs)
  File "C:/Users/rserr/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.6.2/tools/esptool\esptool.py", line 691, in flash_md5sum
    timeout=timeout)
  File "C:/Users/rserr/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.6.2/tools/esptool\esptool.py", line 369, in check_command
    val, data = self.command(op, data, chk, timeout=timeout)
  File "C:/Users/rserr/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.6.2/tools/esptool\esptool.py", line 347, in command
    p = self.read()
  File "C:/Users/rserr/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.6.2/tools/esptool\esptool.py", line 292, in read
    return next(self._slip_reader)
  File "C:/Users/rserr/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.6.2/tools/esptool\esptool.py", line 2045, in slip_reader
    raise FatalError("Timed out waiting for packet %s" % waiting_for)
esptool.FatalError: Timed out waiting for packet header
esptool.FatalError: Timed out waiting for packet header

``

**Comment by devyte** [comment]
@rserroyen We follow an issue template here, which contains specific instructions that you need to follow before submitting an issue. You have completely ignored that.
Please open a new issue, follow the instructions, and pay close attention to the requested information fields. 
Closing due to not compliant.

BTW, your logs show core 2.6.2 which had specific issues. I suggest trying core 2.6.3, and also try latest git to make sure your issue is still valid for the latest core. The instructions for installing latest git are on readthedocs, or you can try @d-a-v 's alpha/beta install instructions, where a snapshot of the core is automatically generated and installed for you.
