### ISSUE TITLE
cant upload on MACOS 

### ISSUE THREAD

**Issue by hznupeter** [esp8266/Arduino#7864]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:				[ESP-12]
- Core Version:			[2.7.4]
- Development Env:		[Arduino IDE]
- Operating System:		[MacOS]

### Settings in IDE

- Module:  			[Wemos D1 R1]
- Flash Mode:			[qio|dio|other]
- Flash Size: 		        [4MB]
- lwip Variant:                 [v2 Lower Memory]
- Flash Frequency:	        [40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:             [115200] 

### Problem Description

Can't upload  on Macos. I've install arduino ide 1.8.13 and the esp8266 is 2.7.4.I cant upload any code to my esp12-f.
I've tried arduino 1.8.10 to 1.8.13 ,and esp8266 from 2.7.0 to 2.7.4 ,all failed.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}

```

### Debug Messages

```
Arduino:1.8.13 (Mac OS X), 开发板："WeMos D1 R1, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory (no features), Disabled, None, Only Sketch, 921600"
Executable segment sizes:
IROM   : 218400          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 26348   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1248  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 680   ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 24776 )         - zeroed variables      (global, static) in RAM/HEAP 
项目使用了 246676 字节，占用了 (23%) 程序存储空间。最大为 1044464 字节。
全局变量使用了26704字节，(32%)的动态内存，余留55216字节局部变量。最大为81920字节。
esptool.py v2.8
Serial port /dev/cu.wchusbserial1420
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: fc:f5:c4:a0:75:70
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Traceback (most recent call last):
  File "/Users/qiujiongtao/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/upload.py", line 65, in <module>
    esptool.main(cmdline)
  File "/Users/qiujiongtao/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool/esptool.py", line 2933, in main
    detect_flash_size(esp, args)
  File "/Users/qiujiongtao/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool/esptool.py", line 2241, in detect_flash_size
    flash_id = esp.flash_id()
  File "/Users/qiujiongtao/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool/esptool.py", line 607, in flash_id
    return self.run_spiflash_command(SPIFLASH_RDID, b"", 24)
  File "/Users/qiujiongtao/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool/esptool.py", line 860, in run_spiflash_command
    set_data_lengths(data_bits, read_bits)
  File "/Users/qiujiongtao/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool/esptool.py", line 837, in set_data_lengths
    self.write_reg(SPI_DATA_LEN_REG,
  File "/Users/qiujiongtao/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool/esptool.py", line 500, in write_reg
    return self.check_command("write target memory", self.ESP_WRITE_REG,
  File "/Users/qiujiongtao/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool/esptool.py", line 369, in check_command
    val, data = self.command(op, data, chk, timeout=timeout)
  File "/Users/qiujiongtao/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool/esptool.py", line 347, in command
    p = self.read()
  File "/Users/qiujiongtao/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool/esptool.py", line 292, in read
    return next(self._slip_reader)
  File "/Users/qiujiongtao/Library/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool/esptool.py", line 2045, in slip_reader
    raise FatalError("Timed out waiting for packet %s" % waiting_for)
esptool.FatalError: Timed out waiting for packet header
esptool.FatalError: Timed out waiting for packet header
```

**Comment by earlephilhower** [comment]
You are having comms trouble with the board.  Suggest trying different USB cables, USB ports, or ESP boards.  This is not a core issue, though, so please use esp8266.com or https://gitter.im/esp8266/Arduino for assistance.
