### ISSUE TITLE
ESP8266

### ISSUE THREAD

**Issue by parimalchaudhary** [esp8266/Arduino#7968]
While uploading the sketch to ESP8266 board , i got error message. Anyone help me pout with this....

Arduino: 1.8.13 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Executable segment sizes:

IROM   : 238104          - code in flash         (default or ICACHE_FLASH_ATTR) 

IRAM   : 28792   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 

DATA   : 1248  )         - initialized variables (global, static) in RAM/HEAP 

RODATA : 760   ) / 81920 - constants             (global, static) in RAM/HEAP 

BSS    : 25320 )         - zeroed variables      (global, static) in RAM/HEAP 

Sketch uses 268904 bytes (25%) of program storage space. Maximum is 1044464 bytes.

Global variables use 27328 bytes (33%) of dynamic memory, leaving 54592 bytes for local variables. Maximum is 81920 bytes.

esptool.py v2.8

Serial port COM3

Connecting....

Chip is ESP8266EX

Features: WiFi

WARNING: Detected crystal freq 20.39MHz is quite different to normalized freq 26MHz. Unsupported crystal in use?

Crystal is 26MHz

MAC: 00:08:ff:00:00:00

Uploading stub...

Running stub...

Traceback (most recent call last):

  File "C:\Users\DGVCL_ITD\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4/tools/upload.py", line 65, in <module>

    esptool.main(cmdline)

  File "C:/Users/DGVCL_ITD/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool\esptool.py", line 2909, in main

    esp = esp.run_stub()

  File "C:/Users/DGVCL_ITD/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool\esptool.py", line 637, in run_stub

    p = self.read()

  File "C:/Users/DGVCL_ITD/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool\esptool.py", line 292, in read

    return next(self._slip_reader)

  File "C:/Users/DGVCL_ITD/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool\esptool.py", line 2057, in slip_reader

    raise FatalError('Invalid head of packet (0x%s)' % hexify(b))

esptool.FatalError: Invalid head of packet (0x46)

esptool.FatalError: Invalid head of packet (0x46)

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by parimalchaudhary** [comment]
Done
