### ISSUE TITLE
Version 3.0.2 fails to link with any sketch. V3.0.1 works fine.

### ISSUE THREAD

**Issue by SteveRMann** [esp8266/Arduino#8352]
### Basic Infos

- [ √] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ √] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ √] I have tested that the issue is present in current master branch (aka latest git).
- [ √] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ √] I have filled out all fields below.

#### Platform

- Hardware:	Wemos d1 mini
- Core Version:  3.0.2
- Development Env:  Arduino IDE
- Operating System:  Windows 10

### Settings in IDE

- Module:              Wemos D1 mini r2
- Flash Mode:        unknown
- Flash Size:           4MB
- lwip Variant:        [unknown]
- Reset Method:    [unknown]
- Flash Frequency: [unknown]
- CPU Frequency:  80Mhz
- Upload Using:     SERIAL
- Upload Speed:   921600

### Problem Description
Using Version 3.0.2 of the ESP boards (in the IDE Boards Manager) produces link errors in all sketches, even the example 'blink' sketch.  The same sketches compile and link OK for the Uno, but all fail when compiled for the Wemos D1 Mini.

The problem developed in the middle of an ongoing project.  I took a dinner break and when I returned, nothing would compile.

Reinstalled Version 3.0.1 and the problem goes away.

### Sketch
As stated in the description, this link error presents for any sketch. The error messages are identical.

### Debug Messages

```
Traceback (most recent call last):

  File "C:\Users\steve\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2/tools/elf2bin.py", line 211, in <module>

    sys.exit(main())

  File "C:\Users\steve\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2/tools/elf2bin.py", line 192, in main

    to_addr=4096

  File "C:\Users\steve\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2/tools/elf2bin.py", line 187, in wrapper

    write_bin(out=out, args=args, **kwargs)

  File "C:\Users\steve\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2/tools/elf2bin.py", line 75, in write_bin

    [size, addr] = get_segment_size_addr(elf, segment, args.path)

  File "C:\Users\steve\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2/tools/elf2bin.py", line 47, in get_segment_size_addr

    p = subprocess.Popen([path + '/xtensa-lx106-elf-objdump', '-h', '-j', segment,  elf], stdout=subprocess.PIPE, universal_newlines=True )

  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\subprocess.py", line 775, in __init__

  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\subprocess.py", line 1178, in _execute_child

FileNotFoundError: [WinError 2] The system cannot find the file specified

exit status 1

Error compiling for board LOLIN(WEMOS) D1 R2 & mini.
```

**Comment by SteveRMann** [comment]
UPdate.
The problem recurred using V3.0.1, so I went back another version to V3.0.0 and the problem went away.
For a few compiles, then it came back.
I installed V3.0.2 and the problem went away. For a few minutes.

I can't just reinstall the ESP board every time I want to compile. What could possibly be my problem?

Again, the compile/link works fine on two other PC's, so something on my PC is screwed up. But what? What folder are the boards files installed in?

**Comment by d-a-v** [comment]
> Again, the compile/link works fine on two other PC's, so something on my PC is screwed up. But what? What folder are the boards files installed in?

If the Arduino IDE method is used using the board manager, installed files are inside the [Arduino15](https://support.arduino.cc/hc/en-us/articles/360018448279-Where-can-I-find-the-Arduino15-folder-) directory.
