### ISSUE TITLE
CRC doesn't match, file is corrupted. It may be a temporary problem, please retry later.

### ISSUE THREAD

**Issue by bitpIus** [esp8266/Arduino#8977]
I'm trying to install the ESP8266 in Arduino IDE but i have an issue :

 ```
CRC doesn't match, file is corrupted. It may be a temporary problem, please retry later.
java.lang.RuntimeException: java.lang.Exception: CRC doesn't match, file is corrupted. It may be a temporary problem, please retry later.
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:179)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: CRC doesn't match, file is corrupted. It may be a temporary problem, please retry later.
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:101)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:56)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:108)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:172)
	... 1 more
```
I'm having this error on windows 11. Linux works just fine.

**Comment by mcspr** [comment]
See https://github.com/esp8266/Arduino/issues/630 and https://github.com/arduino/Arduino/issues/5394#issuecomment-249514625
Removing 'staging' downloads dir might help.
